<h1>Registrazione</h1>


<?php 
	
	$form = $this->form;
	$form->prepare();

	$helper = $this->formElementErrors();
	$helper->setMessageOpenFormat('<div class="help-inline error">');
	$helper->setMessageSeparatorString('</div><div class="help-inline">');
	$helper->setMessageCloseString('</div>');
	
?>


<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<?php	echo $this->form()->openTag($form); ?>
			<div class="form-inline">
				<div class="form-group ">
					<?php echo $this->formRow($form->get('nome')); ?>
				</div>
				<div class="form-group ">
					<?php echo $this->formRow($form->get('cognome')); ?>
				</div>
			</div>
			<div class="form-group ">
				<?php echo $this->formRow($form->get('email')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('password')); ?>
				<?php echo $this->formRow($form->get('checkPassword')); ?>
			</div>
			<div class="form-group ">
				<?php echo $this->formRow($form->get('telefono')); ?>
			</div>
			<div class="form-group ">
				<p>Dichiaro di avere preso visione dell' Informativa Privacy e do il consenso al trattamento dei miei dati per le finalità legate al servizio richiesto.</p>
			</div>

			<p class="right">* campi obbligatori</p>

			<?php echo $this->formSubmit($form->get('inviaRegistrazione')); ?>

			<?php	echo $this->form()->closeTag(); ?>

		</div>
	</div>
</div>