<h1>Registrazione</h1>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<form  id="registrazione" role="form">
				<div class="form-inline">
					<div class="form-group ">
						<label for="nome">
							Nome*
						</label>
						<input type="text" class="form-control" name="nome" id="nome" required="required" />
					</div>
					<div class="form-group ">
						<label for="cognome">
							Cognome*
						</label>
						<input type="text" class="form-control" name="cognome" id="cognome" required="required" />
					</div>
				</div>
				<div class="form-group ">
					<label for="email">
						Email*
					</label>
					<input type="email" class="form-control" name="email" id="email" required="required" />
				</div>
				<div class="form-group">
					<label for="Password">
						Password*
					</label>
					<input type="password" class="form-control" name="password" id="password" required="required" />
					<label for="checkPassword">
						Reinserire la Password*
					</label>
					<input type="password" class="form-control" name="checkPassword" id="checkPassword" required="required" />
				</div>
				<div class="form-group ">
					<label for="telefono">
						Telefono o Cellulare
					</label>
					<input type="text" class="form-control" name="telefono" id="telefono" />
				</div>
				<div class="checkbox">
					 
					<label>
						<input type="checkbox" name="privacy" value="1" /> Dichiaro di avere preso visione dell' Informativa Privacy e do il consenso al trattamento dei miei dati per le finalità legate al servizio richiesto. * 
					</label>
				</div> 
				<p class="right">* campi obbligatori</p>
				<button type="button" id="inviaRegistrazione" class="btn btn-primary">
					Submit
				</button>
			</form>

		</div>
	</div>
</div>